# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "100b8d00a664bdba631801cbeef1a13d"
application_url = "https://shopify-app-template-remix-aged-dust-7151.fly.dev"
embedded = true
name = "serialapp"
handle = "serialapp-1"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_inventory,read_assigned_fulfillment_orders,read_merchant_managed_fulfillment_orders,read_third_party_fulfillment_orders"

[auth]
redirect_urls = [
  "https://shopify-app-template-remix-aged-dust-7151.fly.dev/auth/callback",
  "https://shopify-app-template-remix-aged-dust-7151.fly.dev/auth/shopify/callback",
  "https://shopify-app-template-remix-aged-dust-7151.fly.dev/api/auth/callback"
]

[pos]
embedded = false
